<a href="https://colab.research.google.com/github/coopwilliams/Numerical-Python/blob/master/Chapter2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

data = np.array([[1, 2], [3, 4], [5,6]])

In [0]:
#meshgrid can be used to evaluate functions over two variables or more
X = np.array([1, 2, 1])
Y = np.array([1, 2, 3])
Z = np.array([-1, 0, 1])
a, b, c = np.meshgrid(X, Y, Z)

In [6]:
a

array([[[1, 1, 1],
        [2, 2, 2],
        [1, 1, 1]],

       [[1, 1, 1],
        [2, 2, 2],
        [1, 1, 1]],

       [[1, 1, 1],
        [2, 2, 2],
        [1, 1, 1]]])

In [10]:
# slicing multidimensional arrays
f = lambda m, n: n + 15 * m
A = np.fromfunction(f, (6, 6), dtype=int)
A

array([[ 0,  1,  2,  3,  4,  5],
       [15, 16, 17, 18, 19, 20],
       [30, 31, 32, 33, 34, 35],
       [45, 46, 47, 48, 49, 50],
       [60, 61, 62, 63, 64, 65],
       [75, 76, 77, 78, 79, 80]])

In [11]:
A[:2, :2]

array([[ 0,  1],
       [15, 16]])

In [12]:
A[1:3, 2:]

array([[17, 18, 19, 20],
       [32, 33, 34, 35]])

In [14]:
A[1::2, 1::2]


array([[16, 18, 20],
       [46, 48, 50],
       [76, 78, 80]])

In [29]:
# I wonder if there's a way to slice out a "checkerboard" from an array?
A[np.indices(A.shape).sum(axis=0) % 2 == 1]
# Ok this kind of works, but reshaping it won't work with odd-numbered axes

array([ 1,  3,  5, 15, 17, 19, 31, 33, 35, 45, 47, 49, 61, 63, 65, 75, 77,
       79])

In [31]:
# checkerboard
np.indices((8, 8)).sum(axis=0) % 2

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [28]:
# weird checkerboard
np.indices((8, 8)).prod(axis=0) % 4

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 2, 3, 0, 1, 2, 3],
       [0, 2, 0, 2, 0, 2, 0, 2],
       [0, 3, 2, 1, 0, 3, 2, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 2, 3, 0, 1, 2, 3],
       [0, 2, 0, 2, 0, 2, 0, 2],
       [0, 3, 2, 1, 0, 3, 2, 1]])

In [39]:
# can we sum along arbitrary axes?
Q = np.indices((4, 4, 4, 4, 4)).sum(axis=5)
Q[:2, :2, :2, :2, :2]

# yes.

array([[[[[0, 0],
          [0, 0]],

         [[0, 0],
          [0, 0]]],


        [[[4, 4],
          [4, 4]],

         [[4, 4],
          [4, 4]]]],



       [[[[0, 0],
          [0, 0]],

         [[4, 4],
          [4, 4]]],


        [[[0, 0],
          [0, 0]],

         [[4, 4],
          [4, 4]]]]])

In [40]:
# Arithmetic operations
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
x + y


array([[ 6,  8],
       [10, 12]])